from pathlib import Path
text = Path('xaml/inputXML.xaml').read_text(encoding='utf-8')
replacements = {
    ' Clear ': ' 清除 ',
    ' Get Installed Tweaks ': ' 获取已安装调整 ',
    ' Minimal ': ' 最小 ',
    ' Standard ': ' 标准 ',
    '&#x26A0; Offline Mode - No Internet Connection': '&#x26A0; 离线模式 - 无网络连接',
    'About': '关于',
    'Adjust Font Scaling for Accessibility': '为辅助功能调整字体缩放',
    'Apply': '应用',
    'Auto': '自动',
    'Browse': '浏览',
    'Change the Winutil UI Theme': '更改 Winutil 界面主题',
    'Clean &amp; Reset': '清理 &amp; 重置',
    'Config': '配置',
    'Copy': '复制',
    'Cut': '剪切',
    'Dark': '深色',
    'Default Settings': '默认设置',
    'Delete the temporary working directory and reset the interface back to Step 1': '删除临时工作目录并将界面重置回第 1 步',
    'Disable All Updates': '禁用所有更新',
    'Documentation': '文档',
    'Erase &amp; Write to USB': '擦除 &amp; 写入 USB',
    'Export': '导出',
    'Export Selected Elements and copy execution command to clipboard.': '导出所选元素并将执行命令复制到剪贴板。',
    'Exports all drivers from this machine and injects them into install.wim and boot.wim. Recommended for systems with unsupported NVMe or network controllers.': '导出此机器上的所有驱动程序并注入 install.wim 与 boot.wim，推荐用于 NVMe 或网络控制器不受支持的系统。',
    'Follow the Windows Theme': '跟随 Windows 主题',
    'Font Scaling': '字体缩放',
    'Import': '导入',
    'Import Configuration from exported file.': '从导出的文件导入配置。',
    'Inject current system drivers': '注入当前系统驱动',
    'Install': '安装',
    'Large': '大',
    'Light': '浅色',
    'Mount &amp; Verify ISO': '挂载 &amp; 验证 ISO',
    'N/A': '无',
    'No ISO selected...': '尚未选择 ISO...',
    'Open Microsoft Download Page': '打开微软下载页面',
    'Paste': '粘贴',
    'Press Ctrl-F and type app name to filter application list below. Press Esc to reset the filter': '按 Ctrl+F 并输入应用名称以过滤下方列表。按 Esc 重置筛选',
    'Ready. Please select a Windows 11 ISO to begin.': '准备就绪。请选择一个 Windows 11 ISO 开始。',
    'Recommended Selections:': '推荐选项：',
    'Refresh': '刷新',
    'Reset': '重置',
    'Run Tweaks': '运行调整',
    'Run Windows ISO Modification and Creator': '运行 Windows ISO 修改器与创建器',
    'Save as an ISO File': '保存为 ISO 文件',
    'Security Settings': '安全设置',
    'Small': '小',
    'Sponsors': '赞助者',
    'Tweaks': '调整',
    'Undo Selected Tweaks': '撤销所选调整',
    'Updates': '更新',
    'Use Dark Theme': '使用深色主题',
    'Use Light Theme': '使用浅色主题',
    'Win11ISO': 'Win11ISO',
    'WinUtil': 'WinUtil',
    'Write Directly to a USB Drive (ERASES DRIVE)': '直接写入 USB 驱动器（会擦除驱动器）',
}
for old in sorted(replacements.keys(), key=len, reverse=True):
    new = replacements[old]
    if old not in text:
        print(f'MISSING: {old!r}')
    text = text.replace(old, new)
Path('xaml/inputXML.xaml').write_text(text, encoding='utf-8')
